<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HospitalUnitsSeeder extends Seeder
{
    public function run(): void
    {
        $units = [
            // CRITICAL UNITS (Prioritas Tertinggi)
            [
                'unit_code' => 'IGD',
                'unit_name' => 'Instalasi Gawat Darurat',
                'unit_type' => 'Critical',
                'location' => 'Gedung A Lantai 1',
                'pic_user_id' => null, // Sesuaikan dengan user ID
                'is_24_hours' => true,
                'sla_response_minutes' => 15,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'ICU',
                'unit_name' => 'Intensive Care Unit',
                'unit_type' => 'Critical',
                'location' => 'Gedung A Lantai 3',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 15,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'NICU',
                'unit_name' => 'Neonatal Intensive Care Unit',
                'unit_type' => 'Critical',
                'location' => 'Gedung A Lantai 3',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 15,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'OK',
                'unit_name' => 'Instalasi Bedah/Operasi',
                'unit_type' => 'Critical',
                'location' => 'Gedung B Lantai 2',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 30,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'PICU',
                'unit_name' => 'Pediatric Intensive Care Unit',
                'unit_type' => 'Critical',
                'location' => 'Gedung A Lantai 3',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 15,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CLINICAL UNITS
            [
                'unit_code' => 'POLI-UMUM',
                'unit_name' => 'Poliklinik Umum',
                'unit_type' => 'Clinical',
                'location' => 'Gedung C Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 120,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'POLI-ANAK',
                'unit_name' => 'Poliklinik Anak',
                'unit_type' => 'Clinical',
                'location' => 'Gedung C Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 120,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'POLI-GIGI',
                'unit_name' => 'Poliklinik Gigi',
                'unit_type' => 'Clinical',
                'location' => 'Gedung C Lantai 2',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 120,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'POLI-MATA',
                'unit_name' => 'Poliklinik Mata',
                'unit_type' => 'Clinical',
                'location' => 'Gedung C Lantai 2',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 120,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'POLI-JANTUNG',
                'unit_name' => 'Poliklinik Jantung',
                'unit_type' => 'Clinical',
                'location' => 'Gedung C Lantai 2',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 120,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'RWI-VIP',
                'unit_name' => 'Rawat Inap VIP',
                'unit_type' => 'Clinical',
                'location' => 'Gedung D Lantai 3',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 120,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'RWI-KLS1',
                'unit_name' => 'Rawat Inap Kelas 1',
                'unit_type' => 'Clinical',
                'location' => 'Gedung D Lantai 2',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 120,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'RWI-KLS2',
                'unit_name' => 'Rawat Inap Kelas 2',
                'unit_type' => 'Clinical',
                'location' => 'Gedung D Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 120,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // SUPPORT UNITS
            [
                'unit_code' => 'LAB',
                'unit_name' => 'Laboratorium',
                'unit_type' => 'Support',
                'location' => 'Gedung B Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 240,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'RAD',
                'unit_name' => 'Radiologi',
                'unit_type' => 'Support',
                'location' => 'Gedung B Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 240,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'FARM',
                'unit_name' => 'Instalasi Farmasi',
                'unit_type' => 'Support',
                'location' => 'Gedung A Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 240,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'GIZI',
                'unit_name' => 'Instalasi Gizi',
                'unit_type' => 'Support',
                'location' => 'Gedung E Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 240,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'REHAB',
                'unit_name' => 'Rehabilitasi Medik',
                'unit_type' => 'Support',
                'location' => 'Gedung C Lantai 3',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 240,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ADMINISTRATIVE UNITS
            [
                'unit_code' => 'KASIR',
                'unit_name' => 'Kasir/Billing',
                'unit_type' => 'Administrative',
                'location' => 'Gedung A Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 480,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'ADM',
                'unit_name' => 'Administrasi Pendaftaran',
                'unit_type' => 'Administrative',
                'location' => 'Gedung A Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => true,
                'sla_response_minutes' => 480,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'HRD',
                'unit_name' => 'Human Resource Department',
                'unit_type' => 'Administrative',
                'location' => 'Gedung F Lantai 2',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 480,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'KEU',
                'unit_name' => 'Keuangan',
                'unit_type' => 'Administrative',
                'location' => 'Gedung F Lantai 2',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 480,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'IT',
                'unit_name' => 'Information Technology',
                'unit_type' => 'Administrative',
                'location' => 'Gedung F Lantai 1',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 480,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'unit_code' => 'REKMED',
                'unit_name' => 'Rekam Medis',
                'unit_type' => 'Administrative',
                'location' => 'Gedung A Lantai 2',
                'pic_user_id' => null,
                'is_24_hours' => false,
                'sla_response_minutes' => 480,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('hospital_units')->insert($units);
    }
}
